Repository Abdeboskey/rancid-tomatillos, pull requests merged in 2020-08, with the labels that each got.

#4 Create notes for wireframe
  notes.txt
Labels: documentation, good first issue, planning

#9 Feature/abd create inital architecture
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Header.test.js
  src/index.js
Labels: architecture, class component, enhancement, functional component

#17 Me First! --> Feature/abd fetch initial data
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Header/Header.css
  src/Movies/Movies.css
  src/Movies/Movies.js
Labels: enhancement, fetch

#50 Feature/abd movie details component
  notes.txt
  src/App/App.js
  src/Card/Card.js
  src/Login/Login.js
  src/Movie-details/MovieDetails.js
  src/Movie-details/MovieDetails.test.js
  src/Movies/Movies.js
  src/apiCalls.js
  src/scss/_MovieDetails.scss
Labels: architecture, class component, enhancement, fetch

#52 Feature/abd ratings component
  notes.txt
  src/Ratings/Ratings.js
  src/Ratings/Ratings.test.js
  src/scss/_Ratings.scss
Labels: architecture, enhancement, functional component

#51 Feature/eu details component
  src/Details/Details.js
  src/Details/Details.test.js
  src/scss/_Details.scss
Labels: architecture, enhancement, functional component

#54 Feature/abd billboard component
  src/Billboard/Billboard.js
  src/Billboard/Billboard.test.js
  src/scss/_Billboard.scss
Labels: architecture, enhancement, functional component

#55 Feature/eu videos component
  src/Card/Card.js
  src/Videos/Videos.js
  src/Videos/Videos.test.js
  src/scss/_Videos.scss
Labels: architecture, enhancement, functional component

#62 Feature/abd hookup moviedetails
  src/Billboard/Billboard.js
  src/Movie-details/MovieDetails.js
  src/Ratings/Ratings.js
Labels: architecture, class component

#65 Refactor/abd format info
  src/Details/Details.js
  src/Movie-details/MovieDetails.js
  src/Ratings/Ratings.js
Labels: refactor

#68 Testing/eu class components
  src/App/App.test.js
  src/Login/Login.test.js
  src/Movie-details/MovieDetails.js
  src/Movie-details/MovieDetails.test.js
Labels: class component, enhancement, testing

#75 Testing/eu add tests
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.test.js
Labels: enhancement, testing

#72 Testing/eu moviedetails child components
  src/Billboard/Billboard.test.js
  src/Details/Details.test.js
  src/Ratings/Ratings.test.js
  src/Video/Video.js
  src/Video/Video.test.js
  src/Videos/Videos.js
  src/Videos/Videos.test.js
Labels: enhancement, functional component, testing

#85 Feature/abd react router
  package-lock.json
  package.json
  src/App/App.js
  src/Card/Card.js
  src/Header/Header.js
  src/Login/Login.js
  src/Movie-details/MovieDetails.js
  src/Movies/Movies.js
  src/index.js
Labels: enhancement, router

#90 Feature/eu add ratings
  src/App/App.js
  src/Card/Card.js
  src/Header/Header.js
  src/Login/Login.js
  src/Movie-details/MovieDetails.js
  src/Movies/Movies.js
  src/Ratings/Ratings.js
  src/apiCalls.js
Labels: enhancement, fetch

#89 Style/abd movie details
  src/App/App.js
  src/Details/Details.js
  src/Movie-details/MovieDetails.js
  src/scss/_Billboard.scss
  src/scss/_Details.scss
  src/scss/_Header.scss
  src/scss/_MovieDetails.scss
  src/scss/_Ratings.scss
Labels: refactor, scss, style

#99 Debug/abd fix ratings
  src/App/App.js
  src/Card/Card.js
  src/Header/Header.js
  src/Login/Login.js
  src/Movie-details/MovieDetails.js
  src/Movies/Movies.js
  src/Ratings/Ratings.js
  src/apiCalls.js
Labels: bug, refactor

#101 Testing/eu refactor for router
  src/Card/Card.js
  src/Card/Card.test.js
  src/Movies/Movies.js
  src/Movies/Movies.test.js
  src/Ratings/Ratings.js
Labels: testing

#102 Testing/abd refactor
  src/App/App.test.js
  src/Header/Header.js
  src/Header/Header.test.js
  src/Login/Login.test.js
  src/Movie-details/MovieDetails.test.js
Labels: refactor, testing

#103 Styling/abd movie details makeover
  src/Details/Details.js
  src/Login/Login.test.js
  src/Movie-details/MovieDetails.js
  src/Ratings/Ratings.js
  src/Video/Video.js
  src/Videos/Videos.js
  src/Videos/Videos.test.js
  src/scss/_Billboard.scss
  src/scss/_Details.scss
  src/scss/_Header.scss
  src/scss/_MovieDetails.scss
  src/scss/_Ratings.scss
  src/scss/_Video.scss
  src/scss/_Videos.scss
  src/scss/index.scss
Labels: scss, style

#104 Write initial draft of readme #100
  README.md
Labels: documentation, enhancement
