Repository Abdeboskey/rancid-tomatillos, pull requests merged in 2020-09, with the labels that each got.

#111 Feature/abd commenting
  src/App/App.js
  src/Comment/Comment.js
  src/Comment/Comment.test.js
  src/CommentForm/CommentForm.js
  src/CommentForm/CommentForm.test.js
  src/Comments/Comments.js
  src/Comments/Comments.test.js
  src/Movie-details/MovieDetails.js
  src/apiCalls.js
  src/scss/_Comment.scss
  src/scss/_CommentForm.scss
  src/scss/_Comments.scss
  src/scss/_Details.scss
  src/scss/_MovieDetails.scss
  src/scss/index.scss
Labels: architecture, async, class component, enhancement, fetch, functional component, scss, style

#112 Feature/eu favorite filter
  src/App/App.js
  src/Card/Card.js
  src/Movie-details/MovieDetails.js
  src/Movies/Movies.js
  src/Ratings/Ratings.js
  src/apiCalls.js
  src/assets/white-star.png
  src/assets/yellow-star.png
  src/scss/_App.scss
  src/scss/_Card.scss
  src/scss/_Ratings.scss
Labels: enhancement, fetch, router, style

#114 Testing/eu async functions
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.test.js
  src/Header/Header.test.js
  src/Login/Login.test.js
  src/Movie-details/MovieDetails.js
  src/Movies/Movies.test.js
  src/Ratings/Ratings.test.js
Labels: testing

#116 Testing/abd comments
  src/Comments/Comments.test.js
Labels: testing

#115 Cleanup/eu last issues
  README.md
  src/App/App.js
  src/App/App.test.js
  src/Billboard/Billboard.js
  src/Card/Card.js
  src/Header/Header.js
  src/Header/Header.test.js
  src/Login/Login.test.js
  src/Movie-details/MovieDetails.test.js
  src/Movies/Movies.js
  src/apiCalls.js
  src/scss/_App.scss
Labels: bug, documentation, enhancement, refactor

#120 Testing/abd moviedetails revisited
  src/App/App.js
  src/App/App.test.js
  src/Card/Card.js
  src/Movie-details/MovieDetails.js
  src/Movie-details/MovieDetails.test.js
  src/Ratings/Ratings.js
  src/Ratings/Ratings.test.js
Labels: testing
